### ISSUE TITLE
Is there anyway to build this offline? Or could you  please release some binary version?

### ISSUE THREAD

**Issue by zeerd** [svlad-90/DLT-Message-Analyzer#158]
Hello!

Is there anyway to build this offline? Or could you please release some binary version?
My working computer could not access the internet directly.

**Comment by svlad-90** [comment]
Hi @zeerd, thanks for reporting an issue.

Unfortunately, there is no option to build DLT-Message-Analyzer offline. It relies on access to the other public repositories, from where we are fetching the third-party projects, which are used in the build. E.g. gtest ( unit tests ), DMA_Plantuml ( generation of the class diagrams ), DMA_Framework ( access to components infrastructure ), etc.

The idea to build offline contradicts the chosen approach to have easy access to the selected versions of all dependencies. That won't change.

----

Regarding the binary deliveries. There is already a task to release a binary version - https://github.com/svlad-90/DLT-Message-Analyzer/issues/63.

Still, it is not so easy. Especially for Linux.

There is a huge combination of components used to build the DLT-Message-Analyzer:
- Target OS - Windows or Linux
- Linux distribution
- Version of the used dlt-viewer
- Compiler version ( msvc, gcc )
- Qt version ( 5.15.0 )

Currently, I'm checking all the builds via the Github actions on dlt-viewer 2.21.0 + ( msvc 2019 for Windows or any available GCC on ubuntu for Linux ) + Qt 5.15.0. But will it fit everyone's needs? Moreover, you might have a Linux distro or version with incompatible glibc symbols and binary simply won't start.

For sure I can freeze used versions of dlt-viewer and Qt in binary artifacts. As they will be part of the delivery, it should work for any client, which does not care about specific versions of those dependencies. But building against multiple Linux distributions via GitHub actions? I'm not sure that it is possible. And it might be an endless story to maintain such a thing.

On the other side, I do not have enough capacity for deep integration into Linux update repositories, e.g. to have my tool being installed via the apt-get, zypper, pacman, etc.

----

Which OS do you have? If it is Windows 10 - I can provide you the compiled version of the dlt-viewer + DLT-Message-Analyzer. Otherwise, if it is Windows <10 or Linux - there might be no other way around it right now except building it from the source code.

**Comment by zeerd** [comment]
There is a method to get all the repos by `git submodule`.  I tried to modify some CMakeLists.txt for this, but found there are so many FetchContent in different projects. That could be a huge work to change all of them.

BTW, I've found another guy who help me to build a binary version already. Thanks anyway.

**Comment by svlad-90** [comment]
Hi @zeerd, great to hear that you were able to solve your issue. ))
