### ISSUE TITLE
[SEARCH] Filter logs for ECU

### ISSUE THREAD

**Issue by singhgaurav1302** [svlad-90/DLT-Message-Analyzer#174]
**Is your feature request related to a problem? Please describe.**
Large systems have multiple ECU and different ECU can have same AppId or ContextId. As a user I would like to filter the logs also based on ECU Id to limit the number of serach results.

**Describe the solution you'd like**
Support for EcuId + "" + Apid + “ “ + Ctid + “ “ + Payload

**Comment by svlad-90** [comment]
Hi @singhgaurav1302,

First, thanks for your interest in DMA and for creating this issue.

I totally agree with your motivation. Different users might be interested in searching within a different set of columns.

But there would be users, who would like to preserve backward compatibility so that their saved patterns do not break after this issue is fixed. So it should not be changing one hard-coded set of columns to another.

I think it should be possible to select from the set of available columns which of them will participate in the search and which not. That will allow each user to select his favorite set of columns to be constantly used or to select a set, which is most suitable for a certain situation.

I was thinking, about whether such a set of selected columns should be simply a general search setting, or each pattern should be stored with its own set of selected columns.

I think it will be a general setting. Because if the user would make a multi-pattern search, then we will have a contradiction regarding which set of columns to apply to the combined regular expression.

----

The approach is defined. I see how it could be made. I'm quite busy at work right now, so, please, give me around 1-2 weeks. It should be finished by then.

Once again, thanks for creating this issue! ))

**Comment by svlad-90** [comment]
Hi @singhgaurav1302, the issue was fixed.

PR - https://github.com/svlad-90/DLT-Message-Analyzer/pull/177

Updated documentation:

https://github.com/svlad-90/DLT-Message-Analyzer/blob/master/md/search/search.md#how-the-search-string-is-formed
https://github.com/svlad-90/DLT-Message-Analyzer/blob/master/md/search_view/search_view.md#search-columns
