### ISSUE TITLE
Compilation of the plugin fails with "No rule to make target [...] libantlr4-runtime.a"

### ISSUE THREAD

**Issue by vifactor** [svlad-90/DLT-Message-Analyzer#203]
**Describe the bug**
I follow the instructions on how to build and install the plugin and get the following error at compilation step:
`make[2]: *** No rule to make target 'plugin/DLT-Message-Analyzer/dltmessageanalyzerplugin/src/antlr4_runtime/src/antlr4_runtime/runtime/Cpp/dist/libantlr4-runtime.a', needed by 'plugin/DLT-Message-Analyzer/dltmessageanalyzerplugin/src/CMakeFiles/antlr4_PCRE_static_autogen_timestamp_deps'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1716: plugin/DLT-Message-Analyzer/dltmessageanalyzerplugin/src/CMakeFiles/antlr4_PCRE_static_autogen_timestamp_deps.dir/all] Error 2
make: *** [Makefile:156: all] Error 2`

**To Reproduce**
- Clone this dlt-viewer fork https://github.com/svlad-90/dlt-viewer 
- Follow these instructions: https://github.com/svlad-90/DLT-Message-Analyzer/blob/master/md/installation_guide/installation_guide.md
- Compilation fails

**Expected behavior**
Build should not fail

**Desktop (please complete the following information):**
 - Ubuntu 22.04
 - cmake version 3.28.1
 - g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by svlad-90** [comment]
Hi @vifactor, first of all, thanks for reporting this issue.

I was able to reproduce it in the specified environment. Luckily, I'm also using Ubuntu 22.04.

I did the following things:

- I compiled the CMake 3.28.1 from the source code and installed it in my system
- I got the same compilation error

I thought the root cause was the old-style CMake scripting used by the Antlr4 C++ runtime. The core root cause is probably located somewhere there. However, I decided to go the easier way and update the newer CMake to exclude the possibility of the bug within CMake 3.28.1.

**=> I switched to CMake 3.29.6 and discovered this issue was not reproducible after the update.**
**=> Also, it needed to be reproducible with the initial version of the CMake that I was using - 3.22.1.**

This issue looks like a CMake bug. I suggest changing the CMake version to a newer ( or older ) one.

If you follow my advice, remember to clean up your build folder and run the CMake configuration on the dlt-viewer once again to provoke an update of all the files generated by the CMake.

**=> Please let me know whether my proposal is functional for you once you try it out.**

**Comment by vifactor** [comment]
Thanks for your very quick reply! Indeed with other version of cmake (I tried cmake v3.22.0) it worked out. Should I make a PR to installation instructions with this hint?

Btw, I suspect because my system has both Qt6 and Qt5, and I do not explicitly provide Qt version via CMAKE_PREFIX_PATH, I had also issues at configure step. These can be overcome by providing explicit QT_PREFIX:
`cmake -DQT_PREFIX=Qt5 ..`.

Unfortunately, this trick does not work with the "original" dlt viewer, even if I checkout to the recommended 2.25-version tag.

**Comment by svlad-90** [comment]
Hi @vifactor,

> Thanks for your very quick reply! Indeed with other version of cmake (I tried cmake v3.22.0) it worked out. Should I make a PR to installation instructions with this hint?

I've prepared the following PR that extends the documentation:
https://github.com/svlad-90/DLT-Message-Analyzer/pull/204

Please review it and reply whether it meets your expectations. If it does, I'll merge it and close this issue. ))

> Btw, I suspect because my system has both Qt6 and Qt5, and I do not explicitly provide Qt version via CMAKE_PREFIX_PATH, I had also issues at configure step. These can be overcome by providing explicit QT_PREFIX:
cmake -DQT_PREFIX=Qt5 ...

> Unfortunately, this trick does not work with the "original" dlt viewer, even if I checkout to the recommended 2.25-version tag.

Well, to address this issue you will need to contact the dlt-viewer dev team. I'm using their concept of the QT_PREFIX in my implementation.

**Comment by vifactor** [comment]
Your PR looks good, thanks again for fast support!
